package bayern.kickner.ruinborn.tools

import com.badlogic.gdx.tools.texturepacker.TexturePacker
import java.io.File

/**
 * Packs all single frames from `assets-raw/sprites` (generated by `tools/sprites/generate.py`) with the
 * libGDX TexturePacker into `assets/atlas/game.atlas`. The settings are in `assets-raw/sprites/pack.json`.
 */
fun main() {
    val input = File("assets-raw/sprites")
    require(File(input, "pack.json").isFile) { "assets-raw/sprites/pack.json fehlt – zuerst tools/sprites/generate.py ausführen" }
    val output = File("assets/atlas")
    output.listFiles()?.filter { it.name.startsWith("game") }?.forEach { it.delete() }
    TexturePacker.process(input.path, output.path, "game")
    println("Atlas geschrieben: " + output.listFiles()!!.joinToString { it.name })
}
