// GENERATED by tools/sprites/generate.py. Do not edit by hand, regenerate instead.
package bayern.kickner.ruinborn.client.render.gfx

import kotlin.math.sqrt

/**
 * A sprite in the atlas: region name, number of frames (animation or variants), frame duration,
 * pixel size and anchor. The anchor is the ground center of the object, measured from the BOTTOM left.
 */
data class SpriteDef(
    val region: String,
    val frames: Int,
    val frameDuration: Float,
    val loop: Boolean,
    val width: Int,
    val height: Int,
    val anchorX: Int,
    val anchorY: Int,
)

data class AnimSpec(val frames: Int, val frameDuration: Float, val loop: Boolean)

/** Facing of a unit. dx/dy = direction in world (tile) coordinates. */
enum class Dir(val key: String, val dx: Float, val dy: Float) {
    SE("se", 1.0f, 0.0f),
    SW("sw", 0.0f, 1.0f),
    NW("nw", -1.0f, 0.0f),
    NE("ne", 0.0f, -1.0f),
    ;

    companion object {
        /** Closest direction for a movement (dx, dy) in world coordinates. */
        fun fromDelta(dx: Float, dy: Float): Dir {
            val len = sqrt(dx * dx + dy * dy)
            if (len < 1e-6f) return entries.first()
            return entries.maxBy { it.dx * dx / len + it.dy * dy / len }
        }
    }
}

enum class UnitAction(val key: String) {
    IDLE("idle"),
    WALK("walk"),
    ATTACK("attack"),
    WORK("work"),
    DIE("die"),
    DRIVE("drive"),
    WRECK("wreck"),
}

enum class UnitSprite(
    val key: String,
    val width: Int,
    val height: Int,
    val anchorX: Int,
    val anchorY: Int,
    val actions: Map<UnitAction, AnimSpec>,
) {
    SOLDIER("soldier", 80, 60, 40, 19, mapOf(UnitAction.IDLE to AnimSpec(2, 0.5f, true), UnitAction.WALK to AnimSpec(4, 0.13f, true), UnitAction.ATTACK to AnimSpec(3, 0.09f, true), UnitAction.DIE to AnimSpec(4, 0.14f, false))),
    WORKER("worker", 86, 77, 43, 29, mapOf(UnitAction.IDLE to AnimSpec(2, 0.5f, true), UnitAction.WALK to AnimSpec(4, 0.13f, true), UnitAction.WORK to AnimSpec(4, 0.12f, true), UnitAction.DIE to AnimSpec(4, 0.14f, false))),
    ZOMBIE("zombie", 76, 63, 38, 23, mapOf(UnitAction.IDLE to AnimSpec(2, 0.45f, true), UnitAction.WALK to AnimSpec(4, 0.2f, true), UnitAction.ATTACK to AnimSpec(3, 0.13f, true), UnitAction.DIE to AnimSpec(4, 0.14f, false))),
    BRUTE("brute", 102, 84, 51, 31, mapOf(UnitAction.IDLE to AnimSpec(2, 0.5f, true), UnitAction.WALK to AnimSpec(4, 0.24f, true), UnitAction.ATTACK to AnimSpec(3, 0.15f, true), UnitAction.DIE to AnimSpec(4, 0.16f, false))),
    JEEP("jeep", 64, 65, 32, 17, mapOf(UnitAction.IDLE to AnimSpec(2, 0.12f, true), UnitAction.DRIVE to AnimSpec(4, 0.08f, true), UnitAction.WRECK to AnimSpec(1, 1.0f, false))),
    SHOOTER("shooter", 80, 60, 40, 19, mapOf(UnitAction.IDLE to AnimSpec(2, 0.5f, true), UnitAction.WALK to AnimSpec(4, 0.13f, true), UnitAction.ATTACK to AnimSpec(3, 0.09f, true), UnitAction.DIE to AnimSpec(4, 0.14f, false))),
    ;

    fun region(action: UnitAction, dir: Dir): String = "unit/$key/${action.key}_${dir.key}"
}

/** Building. footprint = edge length of the footprint in tiles (1, 2 or 3). */
enum class BuildingSprite(val footprint: Int, val def: SpriteDef) {
    HQ(3, SpriteDef("building/hq", 4, 0.15f, true, 384, 276, 192, 96)),
    FARM(2, SpriteDef("building/farm", 1, 1.0f, false, 256, 161, 128, 64)),
    OIL_PUMP(2, SpriteDef("building/oil_pump", 6, 0.15f, true, 256, 147, 128, 64)),
    STEEL_MILL(2, SpriteDef("building/steel_mill", 4, 0.2f, true, 256, 236, 128, 64)),
    SAWMILL(2, SpriteDef("building/sawmill", 1, 1.0f, false, 256, 147, 128, 64)),
    BARRACKS(2, SpriteDef("building/barracks", 1, 1.0f, false, 256, 140, 128, 64)),
    WAREHOUSE(2, SpriteDef("building/warehouse", 1, 1.0f, false, 256, 153, 128, 64)),
    HOSPITAL(2, SpriteDef("building/hospital", 1, 1.0f, false, 256, 159, 128, 64)),
    LAB(2, SpriteDef("building/lab", 1, 1.0f, false, 256, 151, 128, 64)),
    WATCHTOWER(1, SpriteDef("building/watchtower", 1, 1.0f, false, 128, 146, 64, 32)),
    CONSTRUCTION_1X1(1, SpriteDef("building/construction_1x1", 1, 1.0f, false, 128, 76, 64, 32)),
    CONSTRUCTION_2X2(2, SpriteDef("building/construction_2x2", 1, 1.0f, false, 256, 212, 128, 64)),
    CONSTRUCTION_3X3(3, SpriteDef("building/construction_3x3", 1, 1.0f, false, 384, 302, 192, 96)),
    WALL(2, SpriteDef("building/wall", 1, 1.0f, false, 256, 182, 128, 64)),
    FACTORY(2, SpriteDef("building/factory", 1, 1.0f, false, 256, 165, 128, 64)),
    RANGE(2, SpriteDef("building/range", 1, 1.0f, false, 256, 141, 128, 64)),
    RALLY_POINT(2, SpriteDef("building/rally_point", 4, 0.15f, true, 256, 157, 128, 64)),
    ALLIANCE_CENTER(2, SpriteDef("building/alliance_center", 4, 0.2f, true, 256, 204, 128, 64)),
    NEST(1, SpriteDef("building/nest", 4, 0.25f, true, 128, 68, 64, 32)),
    FIELD_FOOD(1, SpriteDef("building/field_food", 1, 1.0f, false, 128, 66, 64, 32)),
    FIELD_WOOD(1, SpriteDef("building/field_wood", 1, 1.0f, false, 128, 67, 64, 32)),
    FIELD_STEEL(1, SpriteDef("building/field_steel", 1, 1.0f, false, 128, 67, 64, 32)),
}

/** Ground tiles and overlays. For tiles the frames are variants (e.g. GRASS 0..2), not an animation. */
enum class TileSprite(val def: SpriteDef) {
    GRASS(SpriteDef("tile/grass", 3, 1.0f, false, 128, 64, 64, 32)),
    DIRT(SpriteDef("tile/dirt", 1, 1.0f, false, 128, 64, 64, 32)),
    CONCRETE(SpriteDef("tile/concrete", 1, 1.0f, false, 128, 64, 64, 32)),
    ROAD_X(SpriteDef("tile/road_x", 1, 1.0f, false, 128, 64, 64, 32)),
    ROAD_Y(SpriteDef("tile/road_y", 1, 1.0f, false, 128, 64, 64, 32)),
    GRID(SpriteDef("tile/grid", 1, 1.0f, false, 128, 64, 64, 32)),
    VALID(SpriteDef("tile/valid", 1, 1.0f, false, 128, 64, 64, 32)),
    INVALID(SpriteDef("tile/invalid", 1, 1.0f, false, 128, 64, 64, 32)),
    SELECT(SpriteDef("tile/select", 1, 1.0f, false, 128, 64, 64, 32)),
}

enum class DecoSprite(val def: SpriteDef) {
    PINE(SpriteDef("deco/pine", 1, 1.0f, false, 30, 52, 15, 7)),
    TREE(SpriteDef("deco/tree", 1, 1.0f, false, 30, 47, 15, 8)),
    DEAD_TREE(SpriteDef("deco/dead_tree", 1, 1.0f, false, 22, 38, 11, 5)),
    ROCK(SpriteDef("deco/rock", 1, 1.0f, false, 28, 24, 14, 11)),
    BUSH(SpriteDef("deco/bush", 1, 1.0f, false, 28, 21, 14, 7)),
    WRECK(SpriteDef("deco/wreck", 1, 1.0f, false, 42, 33, 21, 10)),
}

enum class IconSprite(val def: SpriteDef) {
    FOOD(SpriteDef("icon/food", 1, 1.0f, false, 64, 64, 32, 32)),
    WOOD(SpriteDef("icon/wood", 1, 1.0f, false, 64, 64, 32, 32)),
    STEEL(SpriteDef("icon/steel", 1, 1.0f, false, 64, 64, 32, 32)),
    OIL(SpriteDef("icon/oil", 1, 1.0f, false, 64, 64, 32, 32)),
    SPEEDUP(SpriteDef("icon/speedup", 1, 1.0f, false, 64, 64, 32, 32)),
    SHIELD(SpriteDef("icon/shield", 1, 1.0f, false, 64, 64, 32, 32)),
    CRATE(SpriteDef("icon/crate", 1, 1.0f, false, 64, 64, 32, 32)),
    BOOK(SpriteDef("icon/book", 1, 1.0f, false, 64, 64, 32, 32)),
    RELOCATE(SpriteDef("icon/relocate", 1, 1.0f, false, 64, 64, 32, 32)),
    SWORD(SpriteDef("icon/sword", 1, 1.0f, false, 64, 64, 32, 32)),
    CLOCK(SpriteDef("icon/clock", 1, 1.0f, false, 64, 64, 32, 32)),
    SCOUT(SpriteDef("icon/scout", 1, 1.0f, false, 64, 64, 32, 32)),
    CHAT(SpriteDef("icon/chat", 1, 1.0f, false, 64, 64, 32, 32)),
    REPORT(SpriteDef("icon/report", 1, 1.0f, false, 64, 64, 32, 32)),
    ALLIANCE(SpriteDef("icon/alliance", 1, 1.0f, false, 64, 64, 32, 32)),
    GEAR(SpriteDef("icon/gear", 1, 1.0f, false, 64, 64, 32, 32)),
    LOCK(SpriteDef("icon/lock", 1, 1.0f, false, 64, 64, 32, 32)),
    RESEARCH(SpriteDef("icon/research", 1, 1.0f, false, 64, 64, 32, 32)),
    HOSPITAL(SpriteDef("icon/hospital", 1, 1.0f, false, 64, 64, 32, 32)),
    GIFT(SpriteDef("icon/gift", 1, 1.0f, false, 64, 64, 32, 32)),
    STAR(SpriteDef("icon/star", 1, 1.0f, false, 64, 64, 32, 32)),
    TROPHY(SpriteDef("icon/trophy", 1, 1.0f, false, 64, 64, 32, 32)),
    TASK(SpriteDef("icon/task", 1, 1.0f, false, 64, 64, 32, 32)),
    MAP(SpriteDef("icon/map", 1, 1.0f, false, 64, 64, 32, 32)),
    BASE(SpriteDef("icon/base", 1, 1.0f, false, 64, 64, 32, 32)),
    TROOPS(SpriteDef("icon/troops", 1, 1.0f, false, 64, 64, 32, 32)),
    HELP(SpriteDef("icon/help", 1, 1.0f, false, 64, 64, 32, 32)),
    POWER(SpriteDef("icon/power", 1, 1.0f, false, 64, 64, 32, 32)),
    HERO_RHEA(SpriteDef("icon/hero_rhea", 1, 1.0f, false, 64, 64, 32, 32)),
    HERO_VIKTOR(SpriteDef("icon/hero_viktor", 1, 1.0f, false, 64, 64, 32, 32)),
    HERO_KAYA(SpriteDef("icon/hero_kaya", 1, 1.0f, false, 64, 64, 32, 32)),
    HERO_BROCK(SpriteDef("icon/hero_brock", 1, 1.0f, false, 64, 64, 32, 32)),
    HERO_NOVA(SpriteDef("icon/hero_nova", 1, 1.0f, false, 64, 64, 32, 32)),
}

enum class FxSprite(val def: SpriteDef) {
    EXPLOSION(SpriteDef("fx/explosion", 6, 0.07f, false, 96, 96, 48, 24)),
}
